version: '3'

volumes:
  webapp:

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: eloquenta
      MYSQL_USER: mariadbuser
      MYSQL_PASSWORD: mariadbpwd
      MYSQL_ROOT_PASSWORD: mariadbrootpwd
    ports:
      - "3306:3306"

  spring:
    image: openjdk:17-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./backend/build/libs:/webapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://eloquenta_mariadb_1:3306/eloquenta
      SPRING_DATASOURCE_USERNAME: mariadbuser
      SPRING_DATASOURCE_PASSWORD: mariadbpwd
      SPRING_LIQUIBASE_URL: jdbc:mariadb://eloquenta_mariadb_1:3306/eloquenta
      SPRING_LIQUIBASE_USER: mariadbuser
      SPRING_LIQUIBASE_PASSWORD: mariadbpwd
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:db/changelog/db-changelog-master.xml
    working_dir: /webapp
    command: ["java","-jar","eloquenta.jar"]

  gradle:
    image: gradle:jdk17-alpine
    volumes:
      - ./backend:/app
      - ./backend/build/libs:/app/output
    working_dir: /app
    command: ["gradle","build"]

  nginx:
    image: nginx:latest
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring

  frontend:
    image: frontend
    ports:
      - 3000:3000
    depends_on:
      - spring
    environment:
      NEXT_PUBLIC_API_URL: https://server.eloquenta.academy
      OPEN_API_KEY: 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

