version: '3'

volumes:
  webapp:

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: eloquenta
      MYSQL_USER: mariadbuser
      MYSQL_PASSWORD: mariadbpwd
      MYSQL_ROOT_PASSWORD: mariadbrootpwd
    ports:
      - "127.0.0.1:3306:3306"

  spring:
    image: openjdk:17-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./backend/build/libs:/webapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/eloquenta
      SPRING_DATASOURCE_USERNAME: mariadbuser
      SPRING_DATASOURCE_PASSWORD: mariadbpwd
    working_dir: /webapp
    command: ["java","-jar","eloquenta.jar"]

  gradle:
    image: gradle:jdk17-alpine
    volumes:
      - ./backend:/app
      - ./backend/build/libs:/app/output
    working_dir: /app
    command: ["gradle","build"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    
